import type { Metadata } from "next";
import { Yusei_Magic } from "next/font/google";
import "./globals.css";
import { IChildren } from "@/types/children.type";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Providers from "@/providers/Providers";

const Yusei = Yusei_Magic({
  variable: "--yusei-magic",
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: IChildren) {
  return (
    <html lang="en">
      <body
        className={`${Yusei.className} flex flex-col min-h-svh antialiased`}
      >
        <Navbar />
        <Providers>
          <main className="py-12 md:py-20 lg:py-24 container">{children}</main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
